development:
  server_url: http://localhost:3000
  server_url_https: https://www.versioneye.com
  s3_projects_bucket: veye_dev_projects
  s3_infographics_bucket: veye_dev_infographics
  aws_s3_access_key_id: AKIAJJVCE2X6JF4UGT3Q
  aws_s3_secret_access_key: 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
  postmark_api_key: f6312dfd-6ef7-406c-9a7b-748586a43371
  github_client_id: 50fb47103b8a3f03b2cd
  github_client_secret: 621051dd2033682449f62a5452a0e54b6c432907
  facebook_client_id: 230574627021570
  facebook_client_secret: d27fb4a5d443f29cfdbddd79638c91a8
  twitter_consumer_key: QUC41adGEitJRMMyBJ7w
  twitter_consumer_secret: 5hI3nV0KLCXsT96gdTV6ntQ76wss76l9yXI4lKmNrCI

test:
  server_url: http://www.versioneye-beta.com
  server_url_https: https://www.versioneye-beta.com
  s3_projects_bucket: veye_test_projects
  s3_infographics_bucket: veye_test_infographics
  aws_s3_access_key_id: AKIAJJVCE2X6JF4UGT3Q
  aws_s3_secret_access_key: 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
  postmark_api_key: f6312dfd-6ef7-406c-9a7b-748586a43371
  github_client_id: 50fb47103b8a3f03b2cd
  github_client_secret: 621051dd2033682449f62a5452a0e54b6c432907
  facebook_client_id: 230574627021570
  facebook_client_secret: d27fb4a5d443f29cfdbddd79638c91a8
  twitter_consumer_key: QUC41adGEitJRMMyBJ7w
  twitter_consumer_secret: 5hI3nV0KLCXsT96gdTV6ntQ76wss76l9yXI4lKmNrCI

production:
  server_url: http://www.versioneye.com
  server_url_https: https://www.versioneye.com
  s3_projects_bucket: veye_prod_projects
  s3_infographics_bucket: veye_prod_infographics
  aws_s3_access_key_id: AKIAJJVCE2X6JF4UGT3Q
  aws_s3_secret_access_key: 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
  postmark_api_key: f6312dfd-6ef7-406c-9a7b-748586a43371
  github_client_id: 50fb47103b8a3f03b2cd
  github_client_secret: 621051dd2033682449f62a5452a0e54b6c432907
  facebook_client_id: 230574627021570
  facebook_client_secret: d27fb4a5d443f29cfdbddd79638c91a8
  twitter_consumer_key: QUC41adGEitJRMMyBJ7w
  twitter_consumer_secret: 5hI3nV0KLCXsT96gdTV6ntQ76wss76l9yXI4lKmNrCI
