
development:
    host: veye_dev
    database: app5054532
    persist_in_safe_mode: true

test:
    host: localhost
    database: veye_test
    persist_in_safe_mode: true

production:
    uri: <%= ENV['MONGOHQ_URL'] %>