
development:
    host: 192.168.100.10 #localhost
    database: test #veye_dev
    persist_in_safe_mode: true

test:
    host: 192.168.100.10 #localhost
    database: test #veye_test
    persist_in_safe_mode: true

production:
    uri: <%= ENV['MONGOHQ_URL'] %>