
development:
    host: localhost
    database: veye_dev
    persist_in_safe_mode: true

test:
    host: localhost
    database: veye_test
    persist_in_safe_mode: true

production:
    uri: <%= ENV['MONGOLAB_URI'] %>