development:
    host: localhost
    database: veye_prod
    persist_in_safe_mode: true

test:
    host: localhost
    database: veye_test
    persist_in_safe_mode: true

production:
    host: localhost
    database: veye_prod
    persist_in_safe_mode: true