
development:    
    host: localhost
    database: veye_dev
    persist_in_safe_mode: true
    raise_not_found_error: false    
    
test:
    host: localhost
    database: veye_test
    persist_in_safe_mode: true

production:
    host: localhost
    database: veye_prod
    persist_in_safe_mode: true